### ISSUE TITLE
Exception when using function boot() in model class

### ISSUE THREAD

**Issue by PHPadawan** [barryvdh/laravel-ide-helper#1102]
### Versions:
- ide-helper Version: 2.8.1
- Laravel Version: 8.9.0
- PHP Version: 7.3

### Description:

Hello,

I'm running into an Exception `Undefined index: App\Models\User - Could not analyze class App\Models\User` when using the following code in my model class and try to  `php artisan ide-helper:models`. 

```
public static function boot() {
   self::creating(function ($self) {
        ...
   });
}
```

Since I'm a kind of beginner can someone enlighten me with what is going on or a workaround?
Thanks in advance :)

Full trace:
```
Exception: Undefined index: App\Models\User
Could not analyze class App\Models\User.

Trace:
#0 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/dseger/D...', 256, Array)
#1 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(170): Illuminate\Database\Eloquent\Model->initializeTraits()
#2 [internal function]: Illuminate\Database\Eloquent\Model->__construct(Array)
#3 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): ReflectionClass->newInstanceArgs(Array)
#4 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build('App\\Models\\User')
#5 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('App\\Models\\User', Array, true)
#6 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('App\\Models\\User', Array)
#7 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('App\\Models\\User', Array)
#8 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(240): Illuminate\Foundation\Application->make('App\\Models\\User')
#9 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(132): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#10 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#11 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#12 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#17 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/symfony/console/Application.php(920): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/dseger/Desktop/Projects/Eos/esrv/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/dseger/Desktop/Projects/Eos/esrv/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}

```

**Comment by mfn** [comment]
You override `\Illuminate\Database\Eloquent\Model::boot`, which itself has logic which is required to properly boot a model, but you're not calling it.

Possible solutions:
- if you _truly_ require to override `boot`, make sure to call it's parent:
  ```php
  public static function boot() {
     parent::boot(); // <---------------- this line added
     self::creating(function ($self) {
          ...
     });
  }
  ```
  See also https://github.com/laravel/framework/blob/5a3f7cfbba20115eddecd3cfa58d5ad5456c59fa/src/Illuminate/Database/Eloquent/Model.php#L212-L215
- Otherwise I think overriding `booted` should be fine, as it seems to be truly just a stub for this, see https://github.com/laravel/framework/blob/5a3f7cfbba20115eddecd3cfa58d5ad5456c59fa/src/Illuminate/Database/Eloquent/Model.php#L261-L269
