### ISSUE TITLE
[PHP8] Could not analyze class X, exception: method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by bramceulemans** [barryvdh/laravel-ide-helper#1108]
### Versions:
- ide-helper Version: v2.8.1
- Laravel Version: v8.17.1 
- PHP Version: 8.0.0

### Description:

When I run `php artisan ide-helper:models --write-mixin --reset --nowrite --phpstorm-noinspections, the following error is given:

```
Exception: Method ReflectionParameter::getClass() is deprecated
Could not analyze class App\Models\Student.

Trace:
#0 C:\src\rij\sdxam\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(887): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\src\rij\sdxam\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(512): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getParameters()
#2 C:\src\rij\sdxam\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(250): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromMethods()
#3 C:\src\rij\sdxam\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(132): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs()
#4 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#5 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\Container.php(610): Illuminate\Container\BoundMethod::call()
#9 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call()
#10 C:\src\rij\sdxam\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#11 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(68): Illuminate\Console\Command->run()
#13 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(28): Illuminate\Console\Command->runCommand()
#14 C:\src\rij\sdxam\app\Console\Commands\AutocompletionCommand.php(46): Illuminate\Console\Command->call()
#15 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\AutocompletionCommand->handle()
#16 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#18 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#19 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Container\Container.php(610): Illuminate\Container\BoundMethod::call()
#20 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call()
#21 C:\src\rij\sdxam\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#22 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#23 C:\src\rij\sdxam\vendor\symfony\console\Application.php(971): Illuminate\Console\Command->run()
#24 C:\src\rij\sdxam\vendor\symfony\console\Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#25 C:\src\rij\sdxam\vendor\symfony\console\Application.php(166): Symfony\Component\Console\Application->doRun()
#26 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#27 C:\src\rij\sdxam\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run()
#28 C:\src\rij\sdxam\artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#29 {main}
```

### Steps To Reproduce:

- Run `php artisan ide-helper:models --write-mixin --reset --nowrite --phpstorm-noinspections`  on PHP 8.0.0

**Comment by mfn** [comment]
Fixed already prepared with https://github.com/barryvdh/laravel-ide-helper/pull/1106
