### ISSUE TITLE
Custom autoloader turns throws when a deprecation notice is encountered

### ISSUE THREAD

**Issue by Nacoma** [barryvdh/laravel-ide-helper#1449]
### Versions:
- ide-helper Version: 2.13.0
- Laravel Version: 10.15.0
- PHP Version: 8.1

### Description:

When resolving a class from the container that would trigger a deprecation error (E_DEPRECATED), the custom autoloader in `MetaCommand` will trigger an unhandled `Symfony\Component\ErrorHandler\Error\FatalError` if there are any `beforeResolvingCallbacks`.

While the deprecation is being handled, Laravel checks `runningUnitTests` which tries to load `"env"` from the container. The custom autoloader throws a `\ReflectionException` resulting in 

```
PHP Fatal error:  Uncaught Symfony\Component\ErrorHandler\Error\FatalError: During inheritance of JsonSerializable: Uncaught ReflectionException: Class 'env' not found. in /home/cody/apps/800com-dev/fails/vendor/barryvdh/laravel-ide-helper/src/Console/MetaCommand.php:158
Stack trace:
#0 [internal function]: Barryvdh\LaravelIdeHelper\Console\MetaCommand->Barryvdh\LaravelIdeHelper\Console\{closure}()
#1 /home/cody/apps/800com-dev/fails/vendor/laravel/framework/src/Illuminate/Container/Container.php(1216): is_subclass_of()
#2 /home/cody/apps/800com-dev/fails/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->fireBeforeResolvingCallbacks()
........
........
```

### Steps To Reproduce:

I likely won't keep the repo up forever so I'm adding notes below for posterity. You can find repro steps here https://github.com/Nacoma/ide-helper-repro/commit/79a08cc15745a268960d7233a6b7184ead46ebf1 or just pull the repository and try it.

Have a class that triggers deprecation notices:

```php
<?php

namespace App;

class DeprecatedClass implements \JsonSerializable
{

    /**
     * @deprecated
     * Should have ReturnTypeWIllChange but let's pretend it's a vendor library.
     */
    public function jsonSerialize()
    {
        return null;
    }
}
```

In any service provider:

```php
<?php

namespace App\Providers;

use App\DeprecatedClass;
use App\Http\Controllers\Controller;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        $this->app->beforeResolving(Controller::class, function () {
            // doesn't matter what happens here.
        });

        // only matters that this is bound.
        $this->app->singleton(DeprecatedClass::class);
    }
}

```

**Comment by Nacoma** [comment]
A potential solution would be to wrap Laravel's error handler to prevent your autoloader from throwing when they're handling an error. Something similar to 

```php
<?php

$loader = include __DIR__ . '/vendor/autoload.php';

class Handler {
    private bool $shouldErrorWhenAutoloading = true;

    public function getHandler(string $method) {
        return fn (...$args) => match ($method) {
            'onException' => $this->onException(...$args),
            'onError' => $this->onError(...$args),
            'autoload' => $this->autoload(...$args),
        };
    }

    public function onException(\Throwable $t)
    {
        throw $t;
    }

    public function onError($level, $message, $file, $line)
    {
        $this->shouldErrorWhenAutoloading = false;
        // forward to laravel's error handler which will call this method when
        // checking before-resolving callbacks
        is_subclass_of('env', Exception::class);

        $this->shouldErrorWhenAutoloading = true;
    }

    public function autoload() {
        if ($this->shouldErrorWhenAutoloading) {
            throw new ReflectionException('do not want this!');
        }

        return null;
    }
}

error_reporting(E_ALL);

$handler = new Handler();

set_exception_handler($handler->getHandler('onException'));

set_error_handler($handler->getHandler('onError'));

spl_autoload_register($handler->getHandler('autoload'));


try {
    // a class with a deprecation warning
    include './class.php';
} catch (\Throwable $t) {
    dd('fail');
}

dd('success');
