### ISSUE TITLE
Writing model docs sometimes throw "Class 'XYZ' not found" exception

### ISSUE THREAD

**Issue by manniL** [barryvdh/laravel-ide-helper#462]
Greetings!

Since I've implemented a custom class (App\Services\Popular), the command `php artisan ide-helper:models -n` sometimes fails. I'm using it after `composer update`, where it fails every time.

> Generating autoload files
> \> post-update-cmd: Illuminate\Foundation\ComposerScripts::postUpdate
> \> post-update-cmd: php artisan ide
> Executing command (CWD): php artisan ide
> Generating optimized class loader
> The compiled services file has been removed.
> A new helper file was written to _ide_helper.php
> A new meta file was written to .phpstorm.meta.php
> 
>                                            
>   [Exception]                              
>   Class 'App\Services\Popular' not found.  
>                                            
> 
> Script php artisan ide handling the post-update-cmd event returned with an error
> 
>                       
>   [RuntimeException]  
>   Error Output:       
>                       

This didn't happen before implementing my custom class, but I can't see an error there. When just issuing `php artisan ide-helper:models -n` it works without problems.

I'm using an own command called `artisan ide` in the post composer update script, which looks like this:

```
    public function handle()
    {
        if (env("APP_ENV") !== "production") {
            $this->call("optimize");
            $this->call("ide-helper:generate");
            $this->call("ide-helper:meta");
            $this->call("ide-helper:models", ["--nowrite" => true]);
        }
        return;
    }
```

The command worked before without a problem too.

I have no clue how and when the error is issued.

The laravel.log outputs the following stack trace:

> 2017-03-11 18:58:20] local.ERROR: Exception: Class 'App\Services\Popular' not found. in /home/mannil/Programming/PHP/project-website/vendor/barryvdh/laravel-ide-helper/src/Console/MetaCommand.php:127
> Stack trace:
> #0 [internal function]: Barryvdh\LaravelIdeHelper\Console\MetaCommand->Barryvdh\LaravelIdeHelper\Console\{closure}('App\\Services\\Po...')
> #1 [internal function]: spl_autoload_call('App\\Services\\Po...')
> #2 /home/mannil/Programming/PHP/project-website/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(173): class_exists('App\\Services\\Po...')
> #3 /home/mannil/Programming/PHP/project-website/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(95): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
> #4 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->fire()
> #5 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #6 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #7 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
> #8 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
> #9 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
> #10 /home/mannil/Programming/PHP/project-website/vendor/symfony/console/Command/Command.php(265): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
> #11 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
> #12 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Console/Command.php(197): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
> #13 /home/mannil/Programming/PHP/project-website/app/Console/Commands/IdeCommand.php(44): Illuminate\Console\Command->call('ide-helper:mode...', Array)
> #14 [internal function]: App\Console\Commands\IdeCommand->handle()
> #15 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #16 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #17 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
> #18 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
> #19 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
> #20 /home/mannil/Programming/PHP/project-website/vendor/symfony/console/Command/Command.php(265): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #21 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #22 /home/mannil/Programming/PHP/project-website/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #23 /home/mannil/Programming/PHP/project-website/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\IdeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #24 /home/mannil/Programming/PHP/project-website/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #25 /home/mannil/Programming/PHP/project-website/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #26 /home/mannil/Programming/PHP/project-website/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #27 {main}  
>

**Comment by manniL** [comment]
Well, running `composer update -o` worked out. I've dumped autoload before a dozen times and ran `artisan optimize` too. Weird, but it worked :dango:
