### ISSUE TITLE
Method Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::handle() does not exist

### ISSUE THREAD

**Issue by kaxias** [barryvdh/laravel-ide-helper#539]
- Laravel 5.5-dev
- IDEHelper 2.4.0
- Composer 1.4.2 

````shell
 $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: laravel/tinker
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: fideloper/proxy
Package manifest generated successfully.
> @php artisan ide-helper:generate
  [ReflectionException]
  Method Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::handle() does not exist
Script @php artisan ide-helper:generate handling the post-autoload-dump event returned with error code 1
````

**Comment by JanWeskamp** [comment]
Same Problem here .....

attach laravel log file:

 `[2017-07-13 14:24:12] local.ERROR: Method Barryvdh\LaravelIdeHelper\Console\MetaCommand::handle() does not exist {"exception":"[object] (ReflectionException(code: 0): Method Barryvdh\\LaravelIdeHelper\\Console\\MetaCommand::handle() does not exist at /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:135)
[stacktrace]
#0 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(135): ReflectionMethod->__construct(Object(Barryvdh\\LaravelIdeHelper\\Console\\MetaCommand), 'handle')
#1 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(115): Illuminate\\Container\\BoundMethod::getCallReflector(Array)
#2 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\\Container\\BoundMethod::getMethodDependencies(Object(Illuminate\\Foundation\\Application), Array, Array)
#3 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#7 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/symfony/console/Application.php(869): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/symfony/console/Application.php(223): Symfony\\Component\\Console\\Application->doRunCommand(Object(Barryvdh\\LaravelIdeHelper\\Console\\MetaCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/symfony/console/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /Users/janweskamp/PhpstormProjects/Laravel/jtl-dashboard55/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} `

**Comment by Zwaen91** [comment]
Me 2

**Comment by kaxias** [comment]
I think it is laravel framework it is problem.

**Comment by JanWeskamp** [comment]
https://github.com/barryvdh/laravel-ide-helper/pull/540

fire -> handle

-.-

**Comment by vanyaraspopov** [comment]
Adding method in \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand resolves the problem
```
    public function handle()
    {
        $this->fire();
    }
```

**Comment by mfn** [comment]
I can't reproduce this with a fresh Laravel 5.5 installation and ide-helper
```
~/tmp/laravel $ composer create-project --prefer-dist laravel/laravel:5.5 laravel-5.5
Creating a "laravel/laravel:5.5" project at "./laravel-5.5"
Installing laravel/laravel (v5.5.0)
  - Installing laravel/laravel (v5.5.0): Downloading (100%)
Created project in /Users/neo/tmp/laravel/laravel-5.5
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 78 installs, 0 updates, 0 removals
  - Installing kylekatarnls/update-helper (1.2.1): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.17.1): Loading from cache
  - Installing vlucas/phpdotenv (v2.6.5): Downloading (100%)
  - Installing symfony/css-selector (v5.1.2): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.2): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.17.1): Loading from cache
  - Installing symfony/var-dumper (v3.4.42): Downloading (100%)
  - Installing symfony/routing (v3.4.42): Downloading (100%)
  - Installing symfony/process (v3.4.42): Downloading (100%)
  - Installing psr/log (1.1.3): Loading from cache
  - Installing symfony/debug (v3.4.42): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.17.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.17.1): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/polyfill-php70 (v1.17.1): Downloading (100%)
  - Installing symfony/http-foundation (v3.4.42): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/event-dispatcher (v4.4.10): Loading from cache
  - Installing symfony/polyfill-util (v1.17.1): Downloading (100%)
  - Installing symfony/polyfill-php56 (v1.17.1): Downloading (100%)
  - Installing symfony/http-kernel (v3.4.42): Downloading (100%)
  - Installing symfony/finder (v3.4.42): Downloading (100%)
  - Installing symfony/console (v3.4.42): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.17.1): Loading from cache
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing egulias/email-validator (2.1.18): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Downloading (100%)
  - Installing ramsey/uuid (3.9.3): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing symfony/translation-contracts (v1.1.7): Downloading (100%)
  - Installing symfony/translation (v4.3.11): Downloading (100%)
  - Installing nesbot/carbon (1.39.1): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.3): Loading from cache
  - Installing monolog/monolog (1.25.4): Downloading (100%)
  - Installing league/flysystem (1.0.69): Loading from cache
  - Installing erusev/parsedown (1.7.4): Loading from cache
  - Installing doctrine/inflector (1.4.3): Downloading (100%)
  - Installing laravel/framework (v5.5.49): Downloading (100%)
  - Installing fideloper/proxy (3.3.4): Downloading (100%)
  - Installing jakub-onderka/php-console-color (v0.2): Downloading (100%)
  - Installing jakub-onderka/php-console-highlighter (v0.4): Downloading (100%)
  - Installing nikic/php-parser (v4.5.0): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Loading from cache
  - Installing psy/psysh (v0.9.12): Downloading (100%)
  - Installing laravel/tinker (v1.0.10): Downloading (100%)
  - Installing filp/whoops (2.7.3): Downloading (100%)
  - Installing fzaninotto/faker (v1.9.1): Downloading (100%)
  - Installing hamcrest/hamcrest-php (v1.2.2): Downloading (100%)
  - Installing mockery/mockery (0.9.11): Downloading (100%)
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.2): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing doctrine/instantiator (1.3.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing webmozart/assert (1.9.0): Loading from cache
  - Installing phpdocumentor/reflection-common (2.1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.1.0): Loading from cache
  - Installing phpspec/prophecy (v1.10.3): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.9.5): Loading from cache
  - Installing phpunit/phpunit (6.5.14): Loading from cache
symfony/var-dumper suggests installing ext-symfony_debug
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/console suggests installing symfony/lock
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing paragonie/random-lib (Provides RandomLib for use with the RandomLibAdapter)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.5).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use Flysystem caching (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.3).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (~1.0).)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan key:generate
Application key [base64:R3Z2CD3E+gAVWExY8gCnP7XQHACRccSLzlYxuraOYTs=] set successfully.

~/tmp/laravel $ cd laravel-5.5/

~/tmp/laravel/laravel-5.5 $ composer require --dev barryvdh/laravel-ide-helper
Using version ^2.7 for barryvdh/laravel-ide-helper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/cache (1.10.1): Loading from cache
  - Installing doctrine/dbal (2.10.2): Loading from cache
  - Installing seld/phar-utils (1.1.0): Loading from cache
  - Installing seld/jsonlint (1.8.0): Loading from cache
  - Installing justinrainbow/json-schema (5.2.10): Loading from cache
  - Installing composer/xdebug-handler (1.4.2): Loading from cache
  - Installing composer/spdx-licenses (1.5.3): Loading from cache
  - Installing composer/semver (1.5.1): Loading from cache
  - Installing composer/ca-bundle (1.2.7): Loading from cache
  - Installing symfony/filesystem (v5.1.2): Loading from cache
  - Installing composer/composer (1.10.8): Downloading (100%)
  - Installing barryvdh/reflection-docblock (v2.0.6): Loading from cache
  - Installing barryvdh/laravel-ide-helper (v2.7.0): Downloading (100%)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.
33 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

~/tmp/laravel/laravel-5.5 $ ./artisan ide-helper:generate
A new helper file was written to _ide_helper.php
```

5.5 did in fact rename `->fire()` to `->handle()`, as documented in https://laravel.com/docs/5.5/upgrade

Maybe it took ide-helper longer but nowadays the method is called handle and, as I could test, it works.

@barryvdh IMHO nothing to be done (anymore), issue can be closed :}
