### ISSUE TITLE
lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php on line 88 and exactly 1 expected in /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php:77

### ISSUE THREAD

**Issue by oknixus** [barryvdh/laravel-ide-helper#674]
I run `php artisan ide-helper:generate` first, everything is ok. But I am being thrown a lumen.ERROR just now.
the error in the terminal:
![image](https://user-images.githubusercontent.com/4592706/41459566-80d2c912-70bc-11e8-9b3d-597a5e4798ca.png)

and the error's logs:
```
[2018-06-15 16:36:15] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php on line 88 and exactly 1 expected in /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php:77
Stack trace:
#0 /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php(88): Illuminate\Support\Manager->createDriver()
#1 /Users/Home/Valet/small_program/vendor/illuminate/support/Manager.php(63): Illuminate\Support\Manager->createDriver('')
#2 /Users/Home/Valet/small_program/vendor/illuminate/mail/MailServiceProvider.php(95): Illuminate\Support\Manager->driver()
#3 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(749): Illuminate\Mail\MailServiceProvider->Illuminate\Mail\{closure}(Object(Laravel\Lumen\Application), Array)
#4 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#5 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('swift.mailer', Array)
#6 /Users/Home/Valet/small_program/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('swift.mailer', Array)
#7 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(1195): Laravel\Lumen\Application->make('swift.mailer')
#8 /Users/Home/Valet/small_program/vendor/illuminate/mail/MailServiceProvider.php(47): Illuminate\Container\Container->offsetGet('swift.mailer')
#9 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(749): Illuminate\Mail\MailServiceProvider->Illuminate\Mail\{closure}(Object(Laravel\Lumen\Application), Array)
#10 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#11 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('mailer', Array)
#12 /Users/Home/Valet/small_program/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('mailer', Array)
#13 /Users/Home/Valet/small_program/vendor/laravel/lumen-framework/src/Application.php(589): Laravel\Lumen\Application->make('mailer')
#14 /Users/Home/Valet/small_program/app/Providers/AppServiceProvider.php(20): Laravel\Lumen\Application->loadComponent('mail', 'Illuminate\\Mail...', 'mailer')
#15 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(749): App\Providers\AppServiceProvider->App\Providers\{closure}(Object(Laravel\Lumen\Application), Array)
#16 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#17 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('mailer', Array)
#18 /Users/Home/Valet/small_program/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('mailer', Array)
#19 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(1195): Laravel\Lumen\Application->make('mailer')
#20 /Users/Home/Valet/small_program/vendor/illuminate/support/Facades/Facade.php(159): Illuminate\Container\Container->offsetGet('mailer')
#21 /Users/Home/Valet/small_program/vendor/illuminate/support/Facades/Facade.php(128): Illuminate\Support\Facades\Facade::resolveFacadeInstance('mailer')
#22 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Alias.php(225): Illuminate\Support\Facades\Facade::getFacadeRoot()
#23 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Alias.php(47): Barryvdh\LaravelIdeHelper\Alias->detectRoot()
#24 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Generator.php(206): Barryvdh\LaravelIdeHelper\Alias->__construct('Mail', '\\Illuminate\\Sup...', Array, Array)
#25 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Generator.php(227): Barryvdh\LaravelIdeHelper\Generator->getValidAliases()
#26 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Generator.php(84): Barryvdh\LaravelIdeHelper\Generator->getAliasesByExtendsNamespace()
#27 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Generator.php(74): Barryvdh\LaravelIdeHelper\Generator->generatePhpHelper()
#28 /Users/Home/Valet/small_program/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php(113): Barryvdh\LaravelIdeHelper\Generator->generate('php')
#29 [internal function]: Barryvdh\LaravelIdeHelper\Console\GeneratorCommand->handle()
#30 /Users/Home/Valet/small_program/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#31 /Users/Home/Valet/small_program/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#32 /Users/Home/Valet/small_program/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#33 /Users/Home/Valet/small_program/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#34 /Users/Home/Valet/small_program/vendor/illuminate/console/Command.php(183): Illuminate\Container\Container->call(Array)
#35 /Users/Home/Valet/small_program/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 /Users/Home/Valet/small_program/vendor/illuminate/console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#37 /Users/Home/Valet/small_program/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /Users/Home/Valet/small_program/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\GeneratorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /Users/Home/Valet/small_program/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /Users/Home/Valet/small_program/vendor/illuminate/console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /Users/Home/Valet/small_program/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /Users/Home/Valet/small_program/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 {main}
```
that's all the logs
I found  there is nothing in the var `$driver` of vendor/illuminate/support/Manager.php on line 88

then I comment the configuration in the .env:
```
#MAIL_DRIVER=
#MAILGUN_DOMAIL=
#MAILGUN_SECRET=
```
after I did these, the command `php artisan ide-helper:generate` runs ok.
 Waiting for some helps, thanks very much.

**Comment by mfn** [comment]
Is this still an issue with the latest version of Lumen/ide-helper?

**Comment by oknixus** [comment]
Thanks very much. I almost forget this issue.
Thank you. It solved after read this issue [723](https://github.com/barryvdh/laravel-ide-helper/issues/723).
