### ISSUE TITLE
ide-helper models returns error on \App\User model

### ISSUE THREAD

**Issue by abodnar** [barryvdh/laravel-ide-helper#788]
When generating ide_helper models documentation, I get this error:

> Loading model 'App\User'
Exception: Trying to get property 'id' of non-object
Could not analyze class App\User.

Adding -vvv when running the command does not provide any additional information. Nor is there any output in the log file.

Any idea what would be causing this? Other models generate without issues.

**Comment by mfn** [comment]
Can you post the full stacktrace, please?

**Comment by abodnar** [comment]
```
local.DEBUG: #0 /home/vagrant/code/app/User.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/home/vagrant/c...', 210, Array)
#1 /home/vagrant/code/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(494): App\User->dashboardSetting()
#2 /home/vagrant/code/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(215): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromMethods(Object(App\User))
#3 /home/vagrant/code/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(106): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#4 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#5 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#10 /home/vagrant/code/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 /home/vagrant/code/vendor/symfony/console/Application.php(908): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/vagrant/code/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/vagrant/code/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/vagrant/code/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  

```

**Comment by mfn** [comment]
> `#1 /home/vagrant/code/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(494): App\User->dashboardSetting()`

Seems there's some problem with this property/relation or so?

**Comment by abodnar** [comment]
Yeah, looks like former developer thought to have the method not define the relationship, but to have it return a model. Despite the other model defining the relationship.

Thankfully, it's not used very much, so easy to refactor.
