### ISSUE TITLE
error when using composite key package

### ISSUE THREAD

**Issue by MartinP7r** [barryvdh/laravel-ide-helper#838]
#706 seems related

I'm using `awobaz/compoships` (https://github.com/topclaudy/compoships) for a relationship that uses composite keys in one of my models, which seems to break the generation script for models as it throws the following error:

```
Exception: Illegal offset type in isset or empty
Could not analyze class App\ClassName.
```

the breaking composite key relationship looks like this:

```php
public function department()
{
    return $this->hasOne(
        Department::class,
        ['company_id', 'department_id'],
        ['company_id', 'department_id']
    );
}
```

I realize that you can't account for 3rd party packages, but would there be a workaround way to at least exclude the relationship from scanning?

**Comment by mpyw** [comment]
@MartinP7r 

Quick fix for this issue (requires `barryvdh/laravel-ide-helper^2.7` `php>=7.4`):

```php
<?php

namespace App\Console\Commands\IdeHelper;

use Barryvdh\LaravelIdeHelper\Console\ModelsCommand as BaseModelsCommand;
use Illuminate\Support\\Arr;
use Illuminate\Database\Eloquent\Relations\Relation;

class ModelsCommand extends BaseModelsCommand
{
    /**
     * @param  string   $relation
     * @param  Relation $relationObj
     * @return bool
     */
    protected function isRelationNullable(string $relation, Relation $relationObj): bool
    {
        $reflectionObj = new \ReflectionObject($relationObj);

        if (in_array($relation, ['hasOne', 'hasOneThrough', 'morphOne'], true) || !$reflectionObj->hasProperty('foreignKey')) {
            return parent::isRelationNullable($relation, $relationObj);
        }

        $fkProp = $reflectionObj->getProperty('foreignKey');
        $fkProp->setAccessible(true);

        return (bool)Arr::first(
            (array)$fkProp->getValue($relationObj),
            fn (string $value) => isset($this->nullableColumns[$value])
        );
    }
}

```

**Comment by burut13** [comment]
Spostovani,
do torka, 4.8.2020 sem odsoten. Na posto bom odgovoril glede na pomembnost zadeve takoj, ko bo mogoce.
Za nujne zadeve pisite na urgent@u-cart.si ali poklicite +386 40 847 061, Damijan.
Hvala za razumevanje in lep pozdrav,
Borut


Hi there,
I'll be out of office until August 4th 2020. I will reply to your e-mail when I get a chance.
For urgent matters please contact us at urgent@u-cart.si or call +386 40 847 061, Damijan.
Thank you for your understanding and best regards,
Borut

**Comment by musznik** [comment]
error stil exist in "barryvdh/laravel-ide-helper": "^2.10" and "awobaz/compoships": "^2.1",

Trace:
```
Exception: Illegal offset type in isset or empty
Could not analyze class App\Models\MyModel.

#0 \barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(772): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '--', 772, Array)
#1 \barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(734): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->isRelationNullable('belongsTo', Object(Awobaz\Compoships\Database\Eloquent\Relations\BelongsTo))
```

Model:
```
class FirstModel extends Model
{
    use \Awobaz\Compoships\Compoships;

    function commune(){
        return  $this->belongsTo(SecondayModel::class,['WOJ','POW','GMI'],['WOJ','POW','GMI']);
    }
}
```
