### ISSUE TITLE
Exception: Could not find driver

### ISSUE THREAD

**Issue by K2ouMais** [barryvdh/laravel-ide-helper#944]
Hello everyone,

since today I cant generate autocompletion for this specific Model.

```bash
 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead (yes/no) [no]:
 > no

Exception: could not find driver
Could not analyze class App\Models\LEIGleif.

Trace:
#0 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('pgsql:host=wmdb...', 'postgres', 'postgres', Array)
#1 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('pgsql:host=wmdb...', 'postgres', 'postgres', Array)
#2 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connectors\PostgresConnector.php(33): Illuminate\Database\Connectors\Connector->createConnection('pgsql:host=wmdb...', Array, Array)
#3 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(182): Illuminate\Database\Connectors\PostgresConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#6 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(906): Illuminate\Database\Connection->getPdo()
#7 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(892): Illuminate\Database\Connection->getDoctrineConnection()
#8 C:\laragon\www\LEI-API-Frontend\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(360): Illuminate\Database\Connection->getDoctrineSchemaManager('LEIRecords')
#9 C:\laragon\www\LEI-API-Frontend\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(230): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromTable(Object(App\Models\LEIGleif))
#10 C:\laragon\www\LEI-API-Frontend\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(121): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#11 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#12 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array(Array, Array)
#13 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Container\Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#18 C:\laragon\www\LEI-API-Frontend\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 C:\laragon\www\LEI-API-Frontend\vendor\symfony\console\Application.php(1001): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\laragon\www\LEI-API-Frontend\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\laragon\www\LEI-API-Frontend\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\laragon\www\LEI-API-Frontend\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\laragon\www\LEI-API-Frontend\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
Model information was written to _ide_helper_models.php
```

This is my Model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LEIGleif extends Model
{
    protected $connection = 'lei_gleif';
    protected $table = 'LEIRecords';
    protected $guarded = ['*'];

    public static function leiExists($lei)
    {
        if (self::where('LEI', $lei)->count() === 1) {
            return true;
        }

        return false;
    }
}
```

What am I doing wrong? It was working yesterday.

Please let me know if you need more information.

**Comment by K2ouMais** [comment]
Found the reason... Changed my PHP version and the pgsql extension wasnt activated.

Sorry guys...
